### ISSUE TITLE
Error from the beginning

### ISSUE THREAD

**Issue by mihaisalajan** [AndrewMascolo/CountDownTimer#2]
I want to create a timer for Mega 2560 and i found a perfect library , to bad it doesn't work.
please help me.
below, the error mesage:

Arduino: 1.5.5-r2 (Windows 7), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from timer.ino:4:
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:130: error: 'long unsigned int micros()' cannot appear in a constant-expression
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:130: error: a function call cannot appear in a constant-expression
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:130: error: ISO C++ forbids initialization of member 'time'
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:130: error: making 'time' static
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:130: error: ISO C++ forbids in-class initialization of non-const static member 'time'
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:131: error: ISO C++ forbids initialization of member 'Clock'
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:131: error: making 'Clock' static
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:131: error: ISO C++ forbids in-class initialization of non-const static member 'Clock'
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:132: error: ISO C++ forbids initialization of member 'Reset'
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:132: error: making 'Reset' static
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:132: error: ISO C++ forbids in-class initialization of non-const static member 'Reset'
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:132: error: ISO C++ forbids initialization of member 'Stop'
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:132: error: making 'Stop' static
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:132: error: ISO C++ forbids in-class initialization of non-const static member 'Stop'
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:132: error: ISO C++ forbids initialization of member 'Paused'
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:132: error: making 'Paused' static
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:132: error: ISO C++ forbids in-class initialization of non-const static member 'Paused'
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:133: error: ISO C++ forbids initialization of member 'timeFlag'
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:133: error: making 'timeFlag' static
C:\Users\Mihai\Documents\Arduino\libraries\CountUpDownTimer/CountUpDownTimer.h:133: error: ISO C++ forbids in-class initialization of non-const static member 'timeFlag'

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by AndrewMascolo** [comment]
You need to update your IDE version. Try 1.6.0

**Comment by mihaisalajan** [comment]
You are right
i have updated my IDE and i don't have the error anymore, thank you

**Comment by AndrewMascolo** [comment]
Your welcome
