### ISSUE TITLE
It seems there is a problem with large hour numbers

### ISSUE THREAD

**Issue by xseignard** [AndrewMascolo/CountDownTimer#3]
Hello,

First of all thanks for your lib. I'm trying to do a 72h countdown, so I tried the  example using the following `T.SetTimer(72,0,0);`

But the cout down starts with the following time: `17:23:12`

Any idea?

Regards

**Comment by AndrewMascolo** [comment]
The variable "Clock" used to hold the time in seconds, (everything is converted to seconds) is only of type int. You need to make it type long.

**Comment by xseignard** [comment]
See the PR #3
